# file name: Makefile
# author: Ben Silbernagel
# created: winter 2015-2016
# class: Introduction to Computer Science, by Harvard University
# purpose: pset3: make file

fifteen: fifteen.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o fifteen fifteen.c -lcs50 -lm

clean:
	rm -f *.o a.out core fifteen log.txt